version: "3.9"

services:
  flask-app:
    container_name: secure-devsecops-flask

    build: .

    image: secure-devsecops-flask:v1

    restart: unless-stopped

    ports:
      - "5000:5000"

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

    cap_drop:
      - ALL

    pids_limit: 100

    mem_limit: 512m

    cpus: "1.0"
