sonar.projectKey=secure-devsecops-flask
sonar.projectName=Secure DevSecOps Flask
sonar.projectVersion=1.0

# Main source code
sonar.sources=.

# Test directory
sonar.tests=tests

# Exclude tests from main source indexing
sonar.exclusions=tests/**,venv/**,__pycache__/**,.git/**

sonar.python.version=3.14
sonar.sourceEncoding=UTF-8
